// AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
// Generated by tools/gen_detective_data.py from:
//   catalog: data/catalog.author.json (schema_version 1.0.0 / content_version 1.0.0)
//   strings: data/ui_strings.json
//   config:  data/config.json (schema_version 1.0.0)
// Re-run: python tools/gen_detective_data.py
//
// ここに入っているのは設計書 6.2 の「solo パック」＝正解・誤答文・解説・結末まで
// 全部を含む配布物である。オフラインで採点と物語表示を完結させるために必要で、
// 端末を分解すれば答えを読み取れることは設計書が明記している（暗号化はしていない）。
// 社内の気軽なゲームとして運用し、賞金のかかった競技には使わないこと。
//
// 本文は生成時に整形済み: 1 行は全角 13 文字以内、1 ページは 6 行以内。
// LVGL 側は LV_LABEL_LONG_CLIP で幅・高さを指定してそのまま貼るだけでよい。
#pragma once

#include <cstddef>
#include <cstdint>

namespace coffee { namespace det { namespace content {

// 人物（設計書 2.2）。COCOA は第3話の結末にだけ出るので三択には入らない。
enum class Speaker : uint8_t { Narrator = 0, Latte, Mocha, Chai, Cocoa };

// 表情は 4 種だけ（設計書 2.3）。プレイヤーの選択や正誤で変えてはいけない。
enum class Emotion : uint8_t { Neutral = 0, Puzzled, Soft, Smile };

struct Character {
    const char *id;
    const char *name;
    Speaker speaker;
    uint32_t color;      // 設計書 2.4 の初期パレット（0xRRGGBB）
};
extern const Character kCharacters[];
extern const size_t kCharacterCount;
// 見つからなければ nullptr。
const Character *findCharacter(Speaker speaker);

// 本文 1 ページ。text は整形済みで、そのまま lv_label_set_text に渡せる。
struct Page {
    Speaker speaker;
    Emotion emotion;
    const char *text;
};
struct PageRun {
    const Page *pages;
    uint16_t count;
};

struct Option { const char *id; const char *label; };
struct Clue {
    const char *id;
    const char *label;
    PageRun pages;       // 最後のページの「読んだ」で既読になる
    PageRun summary;     // 手帳に並べる要約
};
struct Ambient { const char *id; const char *label; PageRun pages; };
struct Collectible { const char *id; const char *label; const char *text; };

constexpr size_t kClueCount = 3;
constexpr size_t kOptionCount = 3;
constexpr size_t kHintLevels = 2;

struct Episode {
    const char *case_id;
    const char *chapter;        // 第1話
    const char *title;          // 長い題名（整形済み）
    const char *short_title;    // 一覧・見出し用の短い題名
    const char *difficulty;
    const char *teaser;         // 表紙の短い導入コピー（整形済み）
    const char *question;       // 三択の問い（整形済み・2 行以内）
    Option options[kOptionCount];
    PageRun intro;
    PageRun premises;           // 今回の約束
    Clue clues[kClueCount];
    PageRun hints[kHintLevels]; // 段階を飛ばさない。2 段目の最後に結論を足してある
    const Ambient *ambient;
    uint16_t ambient_count;
    uint8_t answer_index;                    // options の添字
    PageRun wrong_feedback[kOptionCount];    // 正解の枠は count == 0
    PageRun explanation;
    PageRun epilogue;
    PageRun recap;              // 章のおわりに並べる 1 行まとめ
    Collectible collectible;
};
extern const Episode kEpisodes[];
extern const size_t kEpisodeCount;

// data/ui_strings.json。見つからなければ nullptr。
// kStrings は元のまま（ボタンの見出しなど 1 行で使うもの）。
// kWrappedStrings は本文欄と同じ規則で折り返したもの（複数文の案内を本文として出すとき）。
struct StringEntry { const char *key; const char *value; };
extern const StringEntry kStrings[];
extern const size_t kStringCount;
const char *findString(const char *key);
extern const StringEntry kWrappedStrings[];
extern const size_t kWrappedStringCount;
const char *findWrappedString(const char *key);

constexpr const char *kPackId = "YOHAKU_CH01";
constexpr const char *kPackTitle = "つづきは、ここで。";
constexpr const char *kWorldTitle = "喫茶「余白」";
constexpr const char *kGameTitle = "CAFE DETECTIVE";
constexpr const char *kContentVersion = "1.0.0";

// 設計書 5.1 の本文欄。生成時の整形もこの値で行っている。
constexpr int16_t kBodyCellsPerLine = 13;
constexpr int16_t kBodyLinesPerPage = 6;
constexpr int16_t kBodyFontPx = 22;
constexpr int16_t kBodyLineHeightPx = 28;

// 読書中の無操作でお話の一覧へ戻るまで（config.json の page_idle_pause_ms）。
constexpr uint32_t kPageIdlePauseMs = 180000;

// 初見の結果にだけ付く点（復習は加算しない）。
constexpr uint8_t kPointsUnassistedCorrect = 2;
constexpr uint8_t kPointsAssistedCorrect = 1;
constexpr uint8_t kPointsIncorrect = 0;

}}} // namespace coffee::det::content
