// AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
// Generated by tools/gen_esper_data.py from:
//   data/catalog.json (schema_version 1.0 / catalog_version ai-esper-ja-1.0.0)
//   SHA-256 6c0024e43cf76ae82d711c4ee42867c8b482f043294dff768ac062533e6650f3
// Re-run: python tools/gen_esper_data.py
//
// 端末の中だけで候補を絞り込むためのデータ（設計書 6.3 のオフライン方式）。
// 候補ビットの並びは catalog.items の配列順そのまま＝ D01 が bit0、T32 が bit127。
// **この並びは保存データにも試験にも効いてくるので絶対に変えない。**
//
// 英語の name_en / meaning_en は入れていない。あれは段階 2 で
// サーバーから Jev へ渡すものなので、端末に持つ必要がない（設計書 9.1）。
//
// 本文は生成時に整形済み: 1 行は全角 13 文字以内。
// LVGL 側は LV_LABEL_LONG_CLIP で幅・高さを指定してそのまま貼るだけでよい。
#pragma once

#include <cstddef>
#include <cstdint>

namespace coffee { namespace esp { namespace content {

// 128 候補の集合。lo が bit0..63（D01..F32）、hi が bit64..127（O01..T32）
struct Mask128 { uint64_t lo; uint64_t hi; };

// 分野（設計書 2.1）。scope_bits の bit0..3 と同じ番号
enum class Group : uint8_t { Drink = 0, Food = 1, Office = 2, Tool = 3 };
constexpr uint8_t kGroupCount = 4;
struct GroupInfo {
    char letter;          // D / F / O / T
    const char *tab;      // 一覧のタブに出す短い名前
    const char *name;     // 見出しに出す名前
    Mask128 items;        // この分野の候補
};
extern const GroupInfo kGroups[kGroupCount];

struct Item {
    const char *id;          // "D01"。画面には出さない（開発用）
    uint8_t group;           // Group の値
    const char *name;        // 表示名（1 行に収まる長さ）
    const char *definition;  // このゲームでの固定の姿（折り返し済み・最大 4 行）
};
extern const Item kItems[];
constexpr uint16_t kItemCount = 128;

struct Question {
    const char *id;        // "Q001"。画面には出さない（開発用）
    const char *text;      // 質問文（折り返し済み・最大 3 行）
    const char *help;      // HELP 画面の補足（折り返し済み・最大 5 行）
    uint16_t text_len;     // 折り返す前の文字数。同点整列の第 2 キー（設計書 3.4）
    uint16_t sort_rank;    // 質問 ID の昇順での順位。同点整列の第 3 キー
    uint8_t scope_bits;    // bit0=D bit1=F bit2=O bit3=T
    Mask128 yes;           // この質問に「はい」となる候補
    Mask128 scope;         // 適用範囲の候補（この外は U＝適用外）
};
extern const Question kQuestions[];
constexpr uint16_t kQuestionCount = 146;

struct Mode {
    const char *id;            // "easy"
    const char *label;         // "EASY"
    const char *name_ja;       // "かんたん"
    const char *summary;       // 候補数・問数・目安時間（折り返し済み）
    Mask128 items;             // 初期候補集合
    uint16_t item_count;
    uint8_t max_questions;     // 最終予想の確認は数に入れない
    uint8_t max_skips;         // 「わからない」の上限
};
extern const Mode kModes[];
// 0〜2 番 = 設計書のモード（手本データの照合用）。3 番から = 端末で遊ぶモード
constexpr uint8_t kRefModeCount = 3;
constexpr uint8_t kPlayModeFirst = 3;
constexpr uint8_t kPlayModeCount = 4;
constexpr uint8_t kModeCount = 7;

// 画面の本文（折り返し済み）。1 行で済むボタンの見出しは EsperGame.cpp 側に直接ある
struct TextEntry { const char *key; const char *value; };
extern const TextEntry kTexts[];
extern const size_t kTextCount;
// 見つからなければ鍵をそのまま返す（画面で気付けるようにするため nullptr にしない）
const char *findText(const char *key);

constexpr const char *kCatalogVersion = "ai-esper-ja-1.0.0";
constexpr const char *kCatalogSha256 = "6c0024e43cf76ae82d711c4ee42867c8b482f043294dff768ac062533e6650f3";
constexpr const char *kRulesVersion = "1.0.0";

// 「1 つ戻る」の上限（設計書 1.4）。skip の上限はモードごとに持つ
constexpr uint8_t kMaxUndo = 2;

// 無操作でひと休みに入るまで（探偵ゲームと同じ 180 秒。設計書 1.4 の 120 秒より
// 長いのは、この端末では状態を捨てずに重ねるだけで、勝敗を付けずに戻れるため）
constexpr uint32_t kIdlePauseMs = 180000;

// 生成時の折り返し幅（EsperGame.cpp の枠と合わせてある）
constexpr int16_t kBodyCellsPerLine = 13;

}}} // namespace coffee::esp::content
