// AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
// Generated by tools/gen_game_data.py from:
//   content: content.ja.json (schema_version 2.0.0)
//   rules:   rules.json (schema_version 2.0.0)
// Re-run: python tools/gen_game_data.py
#pragma once

#include <cstddef>
#include <cstdint>

namespace coffee { namespace wolf { namespace content {

struct StringEntry { const char *key; const char *value; };
extern const StringEntry kStrings[];
extern const size_t kStringCount;
// 線形検索。見つからなければ nullptr を返す。
const char *findString(const char *key);

// id/title/body の3項目を持つページ（tutorial, mandatory_brief で共用）。
struct PagedEntry { const char *id; const char *title; const char *body; };

extern const PagedEntry kTutorial[];
extern const size_t kTutorialCount;

extern const char *const kIntroVariants[];
extern const size_t kIntroVariantCount;

struct EndingVariantGroup { const char *outcome; const char *const *lines; size_t count; };
extern const EndingVariantGroup kEndingVariants[];
extern const size_t kEndingVariantGroupCount;
// 見つからなければ nullptr を返す。
const EndingVariantGroup *findEndingVariants(const char *outcome);

extern const PagedEntry kMandatoryBrief[];
extern const size_t kMandatoryBriefCount;

}}} // namespace coffee::wolf::content

namespace coffee { namespace wolf { namespace rules {

constexpr const char *kSchemaVersion = "2.0.0";
constexpr const char *kGameId = "cafe_werewolf";
constexpr uint8_t kDefaultPlayers = 3;

// 人数ごとの議論時間・決選時間・配札関連の定数。
struct TimingByPlayers {
    uint8_t players;
    uint16_t discussion_s;
    uint16_t runoff_s;
    uint16_t pool_size;
    uint16_t deal_count;
    uint8_t wolf_absent_numerator;
    uint8_t wolf_absent_denominator;
};
extern const TimingByPlayers kTimingByPlayers[];
extern const size_t kTimingByPlayersCount;
// 見つからなければ nullptr を返す。
const TimingByPlayers *findTiming(uint8_t players);

constexpr uint16_t kDiscussionAutoS = 0;
constexpr uint16_t kDiscussionMinS = 90;
constexpr uint16_t kDiscussionMaxS = 600;
constexpr uint16_t kDiscussionStepS = 30;
constexpr uint16_t kDiscussionExtensionS = 60;
constexpr uint8_t kMaxExtensions = 1;
constexpr uint8_t kMaxRunoffs = 1;

constexpr uint32_t kHoldBeforeRevealMs = 500;
constexpr uint32_t kMaxVisibleMs = 8000;
constexpr uint32_t kTouchStaleMs = 200;
constexpr uint32_t kUiTickMs = 20;
constexpr uint32_t kPrivateIdlePauseMs = 60000;
constexpr uint32_t kResultIdleCloseMs = 60000;
constexpr uint64_t kAbsoluteGameLimitMs = 2700000ULL;
constexpr uint32_t kPrivacyHideNormalMaxMs = 120;
constexpr uint32_t kPrivacyHideStaleMaxMs = 250;

constexpr uint8_t kPageSize = 4;
constexpr uint8_t kMandatoryBriefPages = 4;

constexpr const char *kNvsNamespace = "ct_wolf";
constexpr const char *kNvsKey = "meta";
constexpr uint8_t kNvsRecordBytes = 20;
constexpr const char *kNvsMagic = "CTW2";

struct SoundSpec { uint16_t hz; uint16_t ms; };
constexpr SoundSpec kSoundPublicTap = {1600, 30};
constexpr SoundSpec kSoundPublicBoundary = {1200, 70};

}}} // namespace coffee::wolf::rules
