// AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
// Generated by tools/gen_game_data.py from:
//   content: content.ja.json (schema_version 2.0.0)
//   rules:   rules.json (schema_version 2.0.0)
//   layout:  layout.json (schema_version 2.0.0)
// Re-run: python tools/gen_game_data.py
#pragma once

#include <cstddef>
#include <cstdint>

namespace coffee { namespace wolf { namespace content {

struct StringEntry { const char *key; const char *value; };
extern const StringEntry kStrings[];
extern const size_t kStringCount;
// 線形検索。見つからなければ nullptr を返す。
const char *findString(const char *key);

// id/title/body の3項目を持つページ（tutorial, mandatory_brief で共用）。
struct PagedEntry { const char *id; const char *title; const char *body; };

extern const PagedEntry kTutorial[];
extern const size_t kTutorialCount;

extern const char *const kIntroVariants[];
extern const size_t kIntroVariantCount;

struct EndingVariantGroup { const char *outcome; const char *const *lines; size_t count; };
extern const EndingVariantGroup kEndingVariants[];
extern const size_t kEndingVariantGroupCount;
// 見つからなければ nullptr を返す。
const EndingVariantGroup *findEndingVariants(const char *outcome);

extern const PagedEntry kMandatoryBrief[];
extern const size_t kMandatoryBriefCount;

}}} // namespace coffee::wolf::content

namespace coffee { namespace wolf { namespace rules {

constexpr const char *kSchemaVersion = "2.0.0";
constexpr const char *kGameId = "cafe_werewolf";
constexpr uint8_t kDefaultPlayers = 3;

// 人数ごとの議論時間・決選時間・配札関連の定数。
struct TimingByPlayers {
    uint8_t players;
    uint16_t discussion_s;
    uint16_t runoff_s;
    uint16_t pool_size;
    uint16_t deal_count;
    uint8_t wolf_absent_numerator;
    uint8_t wolf_absent_denominator;
};
extern const TimingByPlayers kTimingByPlayers[];
extern const size_t kTimingByPlayersCount;
// 見つからなければ nullptr を返す。
const TimingByPlayers *findTiming(uint8_t players);

constexpr uint16_t kDiscussionAutoS = 0;
constexpr uint16_t kDiscussionMinS = 90;
constexpr uint16_t kDiscussionMaxS = 600;
constexpr uint16_t kDiscussionStepS = 30;
constexpr uint16_t kDiscussionExtensionS = 60;
constexpr uint8_t kMaxExtensions = 1;
constexpr uint8_t kMaxRunoffs = 1;

constexpr uint32_t kHoldBeforeRevealMs = 500;
constexpr uint32_t kMaxVisibleMs = 8000;
constexpr uint32_t kTouchStaleMs = 200;
constexpr uint32_t kUiTickMs = 20;
constexpr uint32_t kPrivateIdlePauseMs = 60000;
constexpr uint32_t kResultIdleCloseMs = 60000;
constexpr uint64_t kAbsoluteGameLimitMs = 2700000ULL;
constexpr uint32_t kPrivacyHideNormalMaxMs = 120;
constexpr uint32_t kPrivacyHideStaleMaxMs = 250;

constexpr uint8_t kPageSize = 4;
constexpr uint8_t kMandatoryBriefPages = 4;

constexpr const char *kNvsNamespace = "ct_wolf";
constexpr const char *kNvsKey = "meta";
constexpr uint8_t kNvsRecordBytes = 20;
constexpr const char *kNvsMagic = "CTW2";

struct SoundSpec { uint16_t hz; uint16_t ms; };
constexpr SoundSpec kSoundPublicTap = {1600, 30};
constexpr SoundSpec kSoundPublicBoundary = {1200, 70};

}}} // namespace coffee::wolf::rules

namespace coffee { namespace wolf { namespace layout {

// data/layout.json の絶対座標（原点は画面左上）。丸型 480x480 の内側に収まるよう検証済み。
struct Rect { int16_t x, y, w, h; };

constexpr int16_t kScreenWidth = 480;
constexpr int16_t kScreenHeight = 480;
constexpr int16_t kSafeCenterX = 240;
constexpr int16_t kSafeCenterY = 240;
constexpr int16_t kSafeRadius = 228;

// 部品ごとの字の大きさ（px）。ファーム側のフォント名との対応はコード側で決める。
constexpr int16_t kFontSizeBody = 22;
constexpr int16_t kFontSizeButton = 22;
constexpr int16_t kFontSizeAuxiliary = 20;
constexpr int16_t kFontSizeRole = 40;
constexpr int16_t kFontSizeTimer = 64;
constexpr int16_t kFontSizeTitle = 20;

constexpr int16_t kBodyCellsPerLine = 13;
constexpr int16_t kBodyLinesPerPage = 4;
constexpr uint8_t kSeatPageSize = 4;

constexpr Rect kTitle{128, 46, 224, 44};
constexpr Rect kCafe{88, 90, 80, 44};
constexpr Rect kHelp{312, 90, 80, 44};
constexpr Rect kBody{90, 144, 300, 128};
constexpr Rect kRoleName{108, 136, 264, 48};
constexpr Rect kSecretBody{90, 192, 300, 106};
constexpr Rect kHold{120, 310, 240, 62};
constexpr Rect kContinue{150, 382, 180, 50};
constexpr Rect kSlot0{76, 142, 154, 64};
constexpr Rect kSlot1{250, 142, 154, 64};
constexpr Rect kSlot2{76, 216, 154, 64};
constexpr Rect kSlot3{250, 216, 154, 64};
constexpr Rect kPagePrev{95, 292, 80, 48};
constexpr Rect kPageLabel{189, 292, 102, 48};
constexpr Rect kPageNext{305, 292, 80, 48};
constexpr Rect kReserveA{97, 350, 136, 54};
constexpr Rect kReserveB{247, 350, 136, 54};
constexpr Rect kPeace{116, 350, 248, 54};
constexpr Rect kSmallNote{133, 413, 214, 28};
constexpr Rect kFooterLeft{106, 361, 124, 50};
constexpr Rect kFooterRight{250, 361, 124, 50};
constexpr Rect kRow0{92, 140, 296, 43};
constexpr Rect kRow1{78, 187, 324, 43};
constexpr Rect kRow2{78, 234, 324, 43};
constexpr Rect kRow3{92, 281, 296, 43};
constexpr Rect kCountNumber{179, 145, 122, 72};
constexpr Rect kCountMinus{80, 225, 125, 58};
constexpr Rect kCountPlus{275, 225, 125, 58};
constexpr Rect kCountHint{118, 293, 244, 36};
constexpr Rect kLargeTimer{114, 155, 252, 86};
constexpr Rect kTimerPrompt{95, 269, 290, 44};
constexpr Rect kWideButton{120, 338, 240, 58};
constexpr Rect kPublicBack{156, 398, 168, 44};

// 席のページ送り（4 枠）と結果画面の行（4 行）は添字で回すことが多いのでまとめておく。
constexpr Rect kSlots[] = {kSlot0, kSlot1, kSlot2, kSlot3};
constexpr Rect kRows[] = {kRow0, kRow1, kRow2, kRow3};

}}} // namespace coffee::wolf::layout
