// AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
// Generated by tools/gen_reversi_data.py — Re-run: python tools/gen_reversi_data.py
#include "ReversiContent.h"

#include <cstdio>
#include <cstring>

namespace coffee { namespace rev { namespace content {

const TextEntry kTexts[] = {
    {"game.title", "JEV REVERSI"},
    {"game.subtitle", "一手ずつ、判断力で勝負。"},
    {"game.menu", "リバーシ"},
    {"start.quick", "QUICK 6×6"},
    {"start.classic", "CLASSIC 8×8"},
    {"start.quick.note", "大きなマスで、気軽に。"},
    {"start.classic.note", "8×8の盤で、じっくり。"},
    {"start.size", "盤面を選ぶ"},
    {"start.side", "あなたの石"},
    {"start.black", "黒・先手"},
    {"start.white", "白・後手"},
    {"start.random", "おまかせ"},
    {"start.opponent", "相手の選び方"},
    {"mode.jev", "JEV"},
    {"mode.pro", "JEV PRO"},
    {"mode.casual", "CASUAL"},
    {"mode.local", "端末AI"},
    {"mode.jev.note", "Jevの最大評価の手で対戦。"},
    {"mode.pro.note", "盤面の特徴もJevへ渡します。"},
    {"mode.casual.note", "Jevの評価分布から手を抽選。"},
    {"mode.local.note", "通信せず、端末内で対戦。"},
    {"mode.notice", "選び方の違いです。強さの順位ではありません。"},
    {"start.go", "始める"},
    {"start.resume", "つづきから"},
    {"start.new", "新しく遊ぶ"},
    {"start.confirm_new", "保存中の対局を終了して始めますか？"},
    {"start.no_online", "Jevに接続できません。端末AIで遊べます。"},
    {"start.no_key", "Jevの接続設定が未完了です。"},
    {"board.black", "黒"},
    {"board.white", "白"},
    {"board.you", "あなた"},
    {"board.ai", "相手"},
    {"board.place", "置く"},
    {"board.menu", "操作"},
    {"board.choices", "候補"},
    {"board.select", "置く場所を選んでください。"},
    {"board.selected", "{coord}を選択中"},
    {"board.illegal", "そこには置けません。"},
    {"board.occupied", "石のある場所には置けません。"},
    {"board.preview", "ここに置くと{count}枚返ります。"},
    {"board.your_turn", "あなたの番"},
    {"board.ai_turn", "相手の番"},
    {"board.saving", "保存中…"},
    {"board.thinking", "Jevが判断中…"},
    {"board.local_thinking", "端末AIが選んでいます。"},
    {"board.only_move", "置ける場所は一つです。"},
    {"board.forced", "ルールによる自動処理"},
    {"pass.you", "あなたは置けないため、パスです。"},
    {"pass.ai", "相手は置けないため、パスです。"},
    {"pass.no_manual", "置ける場所があるときはパスできません。"},
    {"result.win", "あなたの勝ち！"},
    {"result.loss", "相手の勝ち。また一局！"},
    {"result.draw", "引き分け。いい勝負でした。"},
    {"result.empty", "空きマスは、どちらの点にも加えません。"},
    {"result.reason", "両方とも置ける場所がなくなりました。"},
    {"result.resigned", "投了しました。"},
    {"result.aborted", "対局を終了しました。勝敗には数えません。"},
    {"result.jev", "Jevと対戦"},
    {"result.mixed", "一部、端末AIで対戦"},
    {"result.local", "端末AIと対戦"},
    {"result.forced_only", "Jevの選択が発生しなかった対局です。"},
    {"result.again", "もう一局"},
    {"result.home", "カフェへ"},
    {"result.sync_ok", "記録を保存しました。"},
    {"result.sync_wait", "記録は端末に保存。後で送信します。"},
    {"result.sync_failed", "記録を送れませんでした。対局結果は変わりません。"},
    {"menu.continue", "対局へ戻る"},
    {"menu.pause", "保存してカフェへ"},
    {"menu.resign", "投了する"},
    {"menu.end", "対局を終了"},
    {"menu.rules", "遊び方"},
    {"menu.decision", "Jevの評価を見る"},
    {"menu.sound", "操作音"},
    {"menu.resign.confirm", "この対局を負けとして終えますか？"},
    {"menu.end.confirm", "勝敗を付けずに対局を終了しますか？"},
    {"detail.title", "直前のJevの評価"},
    {"detail.notice", "候補間の相対評価です。勝率ではありません。"},
    {"detail.not_reason", "選択分布を表示しています。Jevの内部思考ではありません。"},
    {"detail.none", "表示できるJevの評価はありません。"},
    {"detail.sampled", "CASUALでは評価分布から抽選しました。"},
    {"detail.forced", "この手は一択のため、Jevを呼んでいません。"},
    {"net.slow", "通信に時間がかかっています。"},
    {"net.wait", "もう少し待つ"},
    {"net.retry", "同じ手の結果を確認"},
    {"net.local", "端末AIへ切り替える"},
    {"net.local.confirm", "この対局の残りは端末AIが担当します。Jevへは戻しません。"},
    {"net.pause", "保存して後で続ける"},
    {"net.conflict", "記録が一致しません。安全のため対局を止めました。"},
    {"net.quota", "今日のJev利用枠に達しました。"},
    {"net.bad_response", "Jevの応答を検証できませんでした。"},
    {"net.stale", "古い局面への応答は適用しません。"},
    {"net.tls", "安全な通信を確認できません。接続設定を確認してください。"},
    {"save.resume", "前回の保存時点から再開します。"},
    {"save.corrupt", "保存データを確認できません。新しい対局を始めてください。"},
    {"save.failure", "保存できません。盤面を進めずに停止しました。"},
    {"save.full", "未送信の記録が4件あります。"},
    {"save.drop_old", "最も古い未送信記録を削除"},
    {"save.without_record", "今回は追加の記録を残さず遊ぶ"},
    {"common.yes", "はい"},
    {"common.no", "いいえ"},
    {"common.back", "戻る"},
    {"common.next", "次へ"},
    {"common.ok", "確認"},
    {"pause.idle", "しばらく操作がないため、一時停止しました。"},
    {"pause.not_running", "カフェ表示中は対局を進めません。"},
};
const size_t kTextCount = 105;

const TextEntry kLocalTexts[] = {
    {"start.no_online", "Jevに接続できません。\n端末AIで遊べます。"},
    {"start.no_key", "Jevの接続設定が\n未完了です。"},
    {"start.confirm_new", "保存中の対局を終了して\n始めますか？"},
    {"mode.notice", "選び方の違いです。\n強さの順位ではありません。"},
    {"board.preview", "ここに置くと{count}枚返ります。"},
    {"menu.resign.confirm", "この対局を負けとして\n終えますか？"},
    {"menu.end.confirm", "勝敗を付けずに\n対局を終了しますか？"},
    {"detail.notice", "候補間の相対評価です。\n勝率ではありません。"},
    {"detail.not_reason", "Jevの内部思考ではありません"},
    {"detail.none", "表示できるJevの\n評価はありません。"},
    {"detail.sampled", "評価分布から抽選した手"},
    {"detail.forced", "この手は一択のため、\nJevを呼んでいません。"},
    {"net.local.confirm", "この対局の残りは\n端末AIが担当します。\nJevへは戻しません。"},
    {"net.conflict", "記録が一致しません。\n安全のため対局を止めました。"},
    {"net.bad_response", "Jevの応答を\n検証できませんでした。"},
    {"net.tls", "安全な通信を確認できません。\n接続設定を確認してください。"},
    {"save.corrupt", "保存データを確認できません。\n新しい対局を始めてください。"},
    {"save.failure", "保存できません。\n盤面を進めずに停止しました。"},
    {"pause.idle", "しばらく操作がないため、\n一時停止しました。"},
    {"result.empty", "空きマスは、どちらの点にも\n加えません。"},
    {"result.reason", "両方とも置ける場所が\nなくなりました。"},
    {"result.aborted", "対局を終了しました。\n勝敗には数えません。"},
    {"result.forced_only", "Jevの選択が\n発生しなかった対局です。"},
    {"result.sync_wait", "端末に保存・シートへ送信を依頼"},
    {"result.sync_failed", "端末に保存・シートへは未送信"},
    {"ui.entry.title", "ゲーム"},
    {"ui.entry.no_save", "保存中の対局はありません"},
    {"ui.entry.record", "きろく（勝-敗-分）"},
    {"ui.back_list", "ゲーム一覧へ"},
    {"ui.prev", "前へ"},
    {"ui.menu.title", "操作"},
    {"ui.choices.title", "置ける場所"},
    {"ui.choices.none", "置ける場所がありません。"},
    {"ui.tutorial.title", "遊び方"},
    {"ui.confirm.title", "確認"},
    {"ui.net.title", "通信の状態"},
    {"ui.result.title", "けっか"},
    {"ui.result.ended", "対局を終了"},
    {"ui.detail.chosen", "打った手"},
    {"ui.detail.top", "評価が最大"},
    {"ui.detail.conf", "自信指標"},
    {"ui.detail.cached", "前に決めた手をそのまま"},
    {"ui.board.waiting", "Jevの返事を待っています"},
    {"ui.board.think1", "盤面を読んでいます…"},
    {"ui.board.think2", "手をくらべています…"},
    {"ui.board.think3", "先を読んでいます…"},
    {"ui.board.frozen", "この対局は端末AIが担当"},
    {"ui.board.save_failed", "保存できません"},
    {"ui.detail.more", "ほか"},
    {"ui.net.busy", "前の通信が終わるのを\n待っています。"},
    {"ui.pause.title", "ひと休み"},
    {"ui.pause.resume", "つづける"},
    {"ui.pause.quit", "やめて 一覧へ"},
    {"ui.cafe.title", "カフェ"},
    {"ui.cafe.body", "コーヒーを1杯とりましたか？\n対局は保存されています。"},
    {"ui.cafe.take", "＋1杯を記録"},
    {"ui.cafe.return", "対局へ戻る"},
    {"ui.cafe.home", "HOME へ"},
    {"ui.cafe.added", "＋1杯 記録しました"},
    {"ui.size.label6", "6×6"},
    {"ui.size.label8", "8×8"},
};
const size_t kLocalTextCount = 61;

const TutorialPage kTutorial[] = {
    {"一枚置いて、はさむ",
     "自分の石と新しく置く石で、\n相手の石を一直線にはさみ\nます。はさんだ石が自分の\n色に変わります。"},
    {"八つの方向を確認",
     "縦・横・斜めが対象です。\n一度の着手で複数の方向を\nはさめたら、そのすべてを\n返します。"},
    {"点のある場所が候補",
     "一枚以上返せる空きマスだ\nけに置けます。マスを選び\n「置く」で確定します。候\n補一覧からも選べます。"},
    {"置けないときはパス",
     "置ける場所がなければ、自\n動的に相手の番になります。\n置ける場所があるときは\nパスできません。"},
    {"最後に多い方の勝ち",
     "二人とも置けなくなったら\n終了です。盤上の石が多い\n方が勝ち。同じ枚数なら引\nき分けです。"},
    {"角だけでは決まらない",
     "一度取った角は返されませ\nん。でも、今たくさん返す\n手が、最後に勝つ手とは限\nりません。"},
    {"Jevの判断と対戦",
     "盤面のルールは端末が管理\nし、Jevは合法な候補から\n選びます。表示する評価は、\nこの一局の勝率ではありま\nせん。"},
    {"途中でコーヒーを",
     "メニューから保存してカフェ\nに戻れます。盤面は停止す\nるので、戻ってから続きを\n楽しめます。"},
};

const char *findText(const char *key)
{
    if (key == nullptr) {
        return "";
    }
    for (size_t i = 0; i < kLocalTextCount; ++i) {
        if (std::strcmp(kLocalTexts[i].key, key) == 0) {
            return kLocalTexts[i].value;
        }
    }
    for (size_t i = 0; i < kTextCount; ++i) {
        if (std::strcmp(kTexts[i].key, key) == 0) {
            return kTexts[i].value;
        }
    }
    return key;
}

void formatText(const char *key, const char *coord, unsigned count, char *out, size_t size)
{
    if (out == nullptr || size == 0) {
        return;
    }
    char number[12];
    std::snprintf(number, sizeof(number), "%u", count);
    const char *src = findText(key);
    size_t at = 0;
    while (*src != '\0' && at + 1 < size) {
        const char *fill = nullptr;
        size_t skip = 0;
        if (std::strncmp(src, "{coord}", 7) == 0) {
            fill = coord != nullptr ? coord : "";
            skip = 7;
        } else if (std::strncmp(src, "{count}", 7) == 0) {
            fill = number;
            skip = 7;
        }
        if (fill == nullptr) {
            out[at++] = *src++;
            continue;
        }
        for (const char *p = fill; *p != '\0' && at + 1 < size; ++p) {
            out[at++] = *p;
        }
        src += skip;
    }
    out[at] = '\0';
}

}}} // namespace coffee::rev::content
