// AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
// Generated by tools/gen_reversi_data.py from:
//   data/content.ja.json       SHA-256 817533efc13d9365d870c8deb37176dffd1ecee96588cdd3c645fe991fead813
//   data/tutorial.ja.json      SHA-256 558426c4460612f7a3d48be282c50363668ba4922dc714c4462866865749b718
//   data/content.local.ja.json SHA-256 ff5e85af63ff77b13dbc9f9af10dc88abb8e3245e5e612273f4ddd7bcbe60356
// Re-run: python tools/gen_reversi_data.py
//
// 設計一式（COFFEE_TIME_JEV_REVERSI_Handoff_v1.0.zip）の文言をそのまま持つ。
// 枠に収まらない文言と、設計一式に無い画面の文言は content.local.ja.json 側にあり、
// 同じ鍵なら local が勝つ（findText が local を先に見る）。
//
// 遊び方の本文は生成時に折り返し済み（1 行 全角 12 文字・1 ページ 最大 7 行）。
// LVGL 側は LV_LABEL_LONG_CLIP で幅・高さを指定してそのまま貼るだけでよい。
#pragma once

#include <cstddef>

namespace coffee { namespace rev { namespace content {

// 鍵と文言の組（線形検索。件数が少ないので十分速い）
struct TextEntry { const char *key; const char *value; };
extern const TextEntry kTexts[];          // data/content.ja.json（設計一式）
extern const size_t kTextCount;
extern const TextEntry kLocalTexts[];     // data/content.local.ja.json（追加・上書き）
extern const size_t kLocalTextCount;

// 見つからなければ鍵をそのまま返す（画面で気付けるよう nullptr にしない）
const char *findText(const char *key);

// {coord} と {count} を差し替える（設計一式の board.selected / board.preview 用）。
// 置き換えるものが無ければ元の文言をそのまま写す
void formatText(const char *key, const char *coord, unsigned count, char *out, size_t size);

// 遊び方（設計一式 tutorial.ja.json）。本文は折り返し済み
struct TutorialPage { const char *title; const char *body; };
extern const TutorialPage kTutorial[];
constexpr size_t kTutorialCount = 8;

constexpr const char *kRulesVersion = "1.0.0";
constexpr int kBodyCellsPerLine = 12;    // 生成時の折り返し幅（全角の文字数）

}}} // namespace coffee::rev::content
