"""背景画像を LVGL 8 用の C 配列 (480x480, RGB565) に変換する。

使い方: python tools/img2lvgl.py <入力.png> <出力.c> <変数名> [--dim 0.7]

- 正方形に中央切り抜きして 480x480 に縮小
- 文字を読みやすくするため全体を暗くし（--dim）、上半分をさらに少し暗くする
- LV_COLOR_DEPTH=16 / LV_COLOR_16_SWAP=0 前提（リトルエンディアン RGB565）
"""
import argparse

from PIL import Image

SIZE = 480

ap = argparse.ArgumentParser()
ap.add_argument("src")
ap.add_argument("dst")
ap.add_argument("name")
ap.add_argument("--dim", type=float, default=0.7)
args = ap.parse_args()

img = Image.open(args.src).convert("RGB")
w, h = img.size
side = min(w, h)
img = img.crop(((w - side) // 2, (h - side) // 2, (w + side) // 2, (h + side) // 2))
img = img.resize((SIZE, SIZE), Image.LANCZOS)

px = img.load()
out = bytearray()
for y in range(SIZE):
    # 時計・天気がある上半分は少し強めに暗くする
    k = args.dim * (0.8 + 0.2 * min(1.0, y / (SIZE * 0.5)))
    for x in range(SIZE):
        r, g, b = px[x, y]
        r, g, b = int(r * k), int(g * k), int(b * k)
        v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        out += bytes((v & 0xFF, v >> 8))

with open(args.dst, "w", newline="\n") as f:
    f.write(f"// Generated by tools/img2lvgl.py from {args.src.replace(chr(92), '/').split('/')[-1]}\n")
    f.write("#include \"lvgl.h\"\n\n")
    f.write(f"static const LV_ATTRIBUTE_LARGE_CONST uint8_t {args.name}_map[] = {{\n")
    for i in range(0, len(out), 32):
        f.write("  " + ",".join(f"0x{b:02x}" for b in out[i:i + 32]) + ",\n")
    f.write("};\n\n")
    f.write(f"const lv_img_dsc_t {args.name} = {{\n")
    f.write("  .header = {.cf = LV_IMG_CF_TRUE_COLOR, .always_zero = 0, .reserved = 0,"
            f" .w = {SIZE}, .h = {SIZE}}},\n")
    f.write(f"  .data_size = {len(out)},\n")
    f.write(f"  .data = {args.name}_map,\n")
    f.write("};\n")
print(f"wrote {args.dst} ({len(out)} bytes)")
