"""エスパー対決の推論コアの試験を、この PC（実機なし）で組み立てて実行する。

使い方（PowerShell から）:
    python tools/run_esper_checks.py
    python tools/run_esper_checks.py --keep       # 実行ファイルを消さない
    python tools/run_esper_checks.py --seeds 5    # 乱数試験の seed 数を減らして速く回す

コンパイラーは pip で入れた zig を使う（Visual Studio も MinGW も要らない）:
    python -m pip install --user ziglang
無ければこのスクリプトが入れ方を案内して止まる。

試験の中身は tools/esper_checks.cpp を参照。対象は
  firmware/src/app/games/esper/core/esper_core.hpp   （推論コア）
  firmware/src/app/games/esper/EsperContent.h/.cpp   （生成データ）
だけで、Arduino も LVGL も使っていないのでそのまま PC で動く。

このスクリプトは data/golden_cases.json（設計書の Python 参考実装が出した
168 局の正解記録）を C++ から読める形（esper_golden.inc）に書き出してから
コンパイルする。**質問の並び・残り候補数・最終予想が 1 つでも違えば落ちる。**
"""
import argparse
import json
import os
import pathlib
import subprocess
import sys
import tempfile
import time

ROOT = pathlib.Path(__file__).resolve().parent.parent
GAME_DIR = ROOT / "firmware" / "src" / "app" / "games" / "esper"
DATA_DIR = GAME_DIR / "data"
SOURCE = ROOT / "tools" / "esper_checks.cpp"
CORE = GAME_DIR / "core" / "esper_core.hpp"
CONTENT_CPP = GAME_DIR / "EsperContent.cpp"
CATALOG = DATA_DIR / "catalog.json"
GOLDEN = DATA_DIR / "golden_cases.json"

MODE_ORDER = ["easy", "normal", "hard"]


def zig_version() -> str:
    try:
        out = subprocess.run([sys.executable, "-m", "ziglang", "version"],
                             capture_output=True, text=True, timeout=120)
    except Exception:
        return ""
    return out.stdout.strip() if out.returncode == 0 else ""


def write_golden_inc(path: pathlib.Path) -> int:
    """golden_cases.json を C++ の配列にする（ID を添字へ解決し、照合用に ID も残す）。"""
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    item_index = {x["id"]: n for n, x in enumerate(catalog["items"])}
    question_index = {q["id"]: n for n, q in enumerate(catalog["questions"])}
    cases = json.loads(GOLDEN.read_text(encoding="utf-8"))

    out = []
    a = out.append
    a("// AUTO-GENERATED by tools/run_esper_checks.py — 触らないこと")
    a("// 元データ: firmware/src/app/games/esper/data/golden_cases.json")
    a("struct GoldenStep { const char *qid; uint16_t question; uint8_t yes; uint16_t remaining; };")
    a("struct GoldenCase { uint8_t mode; const char *tid; uint16_t target;")
    a("                    const GoldenStep *steps; uint8_t count; uint16_t expected_guess; };")
    a("")
    for n, case in enumerate(cases):
        a("static const GoldenStep kGoldenSteps%d[] = {" % n)
        for step in case["answers"]:
            a('    {"%s", %d, %d, %d},' % (step["question_id"], question_index[step["question_id"]],
                                           1 if step["answer"] == "yes" else 0,
                                           step["remaining_count"]))
        a("};")
    a("")
    a("static const GoldenCase kGoldenCases[] = {")
    for n, case in enumerate(cases):
        a('    {%d, "%s", %d, kGoldenSteps%d, %d, %d},'
          % (MODE_ORDER.index(case["mode"]), case["target_id"], item_index[case["target_id"]],
             n, len(case["answers"]), item_index[case["expected_guess"]]))
    a("};")
    a("static const int kGoldenCaseCount = %d;" % len(cases))
    a("")
    path.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    return len(cases)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--keep", action="store_true", help="組み立てた実行ファイルを消さない")
    ap.add_argument("--seeds", type=int, default=30,
                    help="乱数で質問を選ぶ試験の seed 数（設計書の参考実装と同じ 30 が既定）")
    args = ap.parse_args()

    for path in (SOURCE, CORE, CONTENT_CPP, CATALOG, GOLDEN):
        if not path.is_file():
            print("試験の元ファイルが見つかりません:", path)
            return 2

    version = zig_version()
    if not version:
        print("zig が見つかりません。次のコマンドで入れてください:")
        print("    python -m pip install --user ziglang")
        return 2
    print(f"zig {version} でコンパイルします")

    out_dir = pathlib.Path(tempfile.mkdtemp(prefix="esper_checks_"))
    inc = out_dir / "esper_golden.inc"
    n_cases = write_golden_inc(inc)
    print(f"golden_cases.json から {n_cases} 局を取り込みました -> {inc.name}")

    exe = out_dir / ("checks.exe" if os.name == "nt" else "checks")
    cmd = [sys.executable, "-m", "ziglang", "c++", "-std=c++17", "-O2",
           "-Wall", "-Wextra", "-Wno-unused-parameter",
           "-I", str(out_dir),
           f"-DESPER_RANDOM_SEEDS={args.seeds}",
           str(SOURCE), str(CONTENT_CPP), "-o", str(exe)]
    t0 = time.time()
    build = subprocess.run(cmd, capture_output=True, text=True)
    if build.stdout.strip():
        print(build.stdout)
    if build.stderr.strip():
        print(build.stderr)
    if build.returncode != 0:
        print("コンパイルに失敗しました")
        return build.returncode
    print(f"コンパイル {time.time() - t0:.1f} 秒\n")

    t1 = time.time()
    run = subprocess.run([str(exe)], text=True)
    elapsed = time.time() - t1
    print(f"\n実行 {elapsed:.1f} 秒")

    if not args.keep:
        try:
            exe.unlink()
            inc.unlink()
            out_dir.rmdir()
        except OSError:
            pass
    else:
        print("残したファイル:", out_dir)
    return run.returncode


if __name__ == "__main__":
    sys.exit(main())
