"""AI DUEL のロジック試験を、この PC（実機なし）で組み立てて実行する。

使い方（PowerShell から）:
    python tools/run_duel_checks.py
    python tools/run_duel_checks.py --keep       # 組み立てた実行ファイルを消さない

コンパイラーは pip で入れた zig を使う（Visual Studio も MinGW も要らない）:
    python -m pip install --user ziglang
無ければこのスクリプトが入れ方を案内して止まる。

試験の中身は tools/duel_checks.cpp を参照。対象は
  firmware/src/app/games/duel/core/duel_core.hpp   （ヘッダーだけの純粋ロジック）
だけで、Arduino も LVGL も使っていないのでそのまま PC で動く。

このスクリプトは
  firmware/src/app/games/duel/data/golden_cases.json  （tools/gen_duel_golden.py が
      設計書の参考実装 duel_reference.py から作った正解データ）
  設計書付属 zip の test_vectors.json の greedy_counterexample
を C++ から読める形（duel_golden.inc）に書き出してからコンパイルする。
**確率・統計・最善手の集合が 1 つでも 1e-9 を超えてずれれば落ちる。**

浮動小数は Python の float.hex()（= C++17 の 16 進浮動小数リテラル）で埋め込むので、
10 進の書き出し・読み直しによる丸めは起きない。
"""
import argparse
import json
import os
import pathlib
import subprocess
import sys
import tempfile
import time
import zipfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
GAME_DIR = ROOT / "firmware" / "src" / "app" / "games" / "duel"
SOURCE = ROOT / "tools" / "duel_checks.cpp"
CORE = GAME_DIR / "core" / "duel_core.hpp"
GOLDEN = GAME_DIR / "data" / "golden_cases.json"
ZIP = ROOT / "参考データ" / "ゲーム4部作" / "COFFEE_TIME_AI_DUEL_Handoff_v1.0.zip"

HANDS = ("ROCK", "SCISSORS", "PAPER")
RESULTS = ("human_win", "ai_win", "draw")
PROVIDERS = ("jev", "stats")


def hexf(x: float) -> str:
    """C++17 の 16 進浮動小数リテラル。10 進を通さないので 1 ビットも狂わない。"""
    return float(x).hex()


def mask_of(names) -> int:
    m = 0
    for n in names:
        m |= 1 << HANDS.index(n)
    return m


def zig_version() -> str:
    try:
        out = subprocess.run([sys.executable, "-m", "ziglang", "version"],
                             capture_output=True, text=True, timeout=120)
    except Exception:
        return ""
    return out.stdout.strip() if out.returncode == 0 else ""


def read_test_vectors() -> dict:
    with zipfile.ZipFile(ZIP) as z:
        name = next((n for n in z.namelist() if n.endswith("test_vectors.json")), None)
        if name is None:
            raise SystemExit("zip の中に test_vectors.json がありません")
        return json.loads(z.read(name).decode("utf-8"))


def write_golden_inc(path: pathlib.Path) -> tuple:
    data = json.loads(GOLDEN.read_text(encoding="utf-8"))
    vectors = read_test_vectors()["greedy_counterexample"]

    out = []
    a = out.append
    a("// AUTO-GENERATED by tools/run_duel_checks.py — 触らないこと")
    a("// 元データ: firmware/src/app/games/duel/data/golden_cases.json")
    a("//           設計書付属 zip の test_vectors.json (greedy_counterexample)")
    a("")

    # --- 設計書 5.4 の反例 ---------------------------------------------------
    a("static const double kVectorProbabilities[3] = {%s};"
      % ", ".join(hexf(vectors["probabilities"][h]) for h in HANDS))
    a("static const double kVectorExpectedMargins[3] = {%s};"
      % ", ".join(hexf(vectors["expected_margins"][h]) for h in HANDS))
    a("static const uint8_t kVectorBest = %d;" % HANDS.index(vectors["best"]))
    a("")

    # --- 正解データ ----------------------------------------------------------
    a("struct GoldenStep {")
    a("    uint16_t match_id; uint8_t round_no;")
    a("    double baseline[3]; uint8_t baseline_optimal;")
    a("    uint8_t provider; double probabilities[3]; uint8_t optimal;")
    a("    uint8_t ai_hand; uint8_t player_hand; uint8_t player_result;")
    a("};")
    a("struct GoldenMatch { uint16_t match_id; uint8_t rounds; };")
    a("struct GoldenTail { uint16_t match_id; uint8_t round_no;")
    a("                    uint8_t player_hand, ai_hand, player_result; };")
    a("struct GoldenStats {")
    a("    uint32_t rounds;")
    a("    uint32_t hand_counts[3], outcome_counts[3], first_hand_counts[3];")
    a("    uint32_t transition_by_hand[9];")
    a("    uint32_t transition_by_hand_result[27];")
    a("    uint32_t repeat_after_result[6];")
    a("    const GoldenTail *tail; uint8_t tail_count;")
    a("    uint32_t pred_n[2], pred_hits[2]; double pred_brier[2], pred_nll[2];")
    a("    uint32_t match_counts[5];")
    a("};")
    a("struct GoldenCase {")
    a("    const GoldenStep *steps; uint16_t step_count;")
    a("    const GoldenMatch *matches; uint8_t match_count;")
    a("    GoldenStats final_stats;")
    a("};")
    a("")

    rounds = 0
    for n, case in enumerate(data["cases"]):
        a("static const GoldenStep kSteps%d[] = {" % n)
        for s in case["steps"]:
            rounds += 1
            a("    {%d,%d, {%s}, %d, %d, {%s}, %d, %d,%d,%d},"
              % (s["match_id"], s["round_no"],
                 ",".join(hexf(x) for x in s["baseline"]), mask_of(s["baseline_optimal"]),
                 PROVIDERS.index(s["provider"]),
                 ",".join(hexf(x) for x in s["probabilities"]), mask_of(s["optimal"]),
                 HANDS.index(s["ai_hand"]), HANDS.index(s["player_hand"]),
                 RESULTS.index(s["player_result"])))
        a("};")
        a("static const GoldenMatch kMatches%d[] = {%s};"
          % (n, "".join("{%d,%d}," % (m["match_id"], m["rounds"]) for m in case["matches"])))
        tail = case["final_stats"]["tail"]
        a("static const GoldenTail kTail%d[] = {%s};"
          % (n, "".join("{%d,%d,%d,%d,%d},"
                        % (t["match_id"], t["round_no"], HANDS.index(t["player_hand"]),
                           HANDS.index(t["ai_hand"]), RESULTS.index(t["player_result"]))
                        for t in tail)))
    a("")

    a("static const GoldenCase kGoldenCases[] = {")
    for n, case in enumerate(data["cases"]):
        st = case["final_stats"]
        tbh = [st["transition_by_hand"][i][j] for i in range(3) for j in range(3)]
        tbhr = [st["transition_by_hand_result"][i][j][k]
                for i in range(3) for j in range(3) for k in range(3)]
        rar = [st["repeat_after_result"][i][j] for i in range(3) for j in range(2)]
        mc = st["match_counts"]
        pred = st["prediction"]
        a("    {kSteps%d, %d, kMatches%d, %d, {%d, {%s},{%s},{%s}, {%s}, {%s}, {%s},"
          % (n, len(case["steps"]), n, len(case["matches"]), st["rounds"],
             ",".join(str(x) for x in st["hand_counts"]),
             ",".join(str(x) for x in st["outcome_counts"]),
             ",".join(str(x) for x in st["first_hand_counts"]),
             ",".join(str(x) for x in tbh), ",".join(str(x) for x in tbhr),
             ",".join(str(x) for x in rar)))
        a("     kTail%d, %d, {%d,%d}, {%d,%d}, {%s}, {%s}, {%d,%d,%d,%d,%d}}},"
          % (n, len(st["tail"]),
             pred["jev"]["n"], pred["stats"]["n"],
             pred["jev"]["hits"], pred["stats"]["hits"],
             ",".join(hexf(pred[p]["brier_sum"]) for p in PROVIDERS),
             ",".join(hexf(pred[p]["nll_sum"]) for p in PROVIDERS),
             mc["completed"], mc["human_win"], mc["ai_win"], mc["draw"], mc["aborted"]))
    a("};")
    a("static const int kGoldenCaseCount = %d;" % len(data["cases"]))
    a("static const int kGoldenRoundCount = %d;" % rounds)
    a('static const char *const kGoldenSource = "%s";' % data["reference"])
    a("static const int kGoldenSeed = %d;" % data["seed"])
    a("")
    path.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    return len(data["cases"]), rounds


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--keep", action="store_true", help="組み立てた実行ファイルを消さない")
    args = ap.parse_args()

    for path in (SOURCE, CORE, GOLDEN, ZIP):
        if not path.is_file():
            print("試験の元ファイルが見つかりません:", path)
            if path is GOLDEN:
                print("  先に python tools/gen_duel_golden.py を実行してください")
            return 2

    version = zig_version()
    if not version:
        print("zig が見つかりません。次のコマンドで入れてください:")
        print("    python -m pip install --user ziglang")
        return 2
    print(f"zig {version} でコンパイルします")

    out_dir = pathlib.Path(tempfile.mkdtemp(prefix="duel_checks_"))
    inc = out_dir / "duel_golden.inc"
    n_cases, n_rounds = write_golden_inc(inc)
    print(f"golden_cases.json から {n_cases} 局 / {n_rounds} ラウンドを取り込みました"
          f" -> {inc.name}")

    exe = out_dir / ("checks.exe" if os.name == "nt" else "checks")
    cmd = [sys.executable, "-m", "ziglang", "c++", "-std=c++17", "-O2",
           "-Wall", "-Wextra", "-Wno-unused-parameter",
           "-I", str(out_dir), str(SOURCE), "-o", str(exe)]
    t0 = time.time()
    build = subprocess.run(cmd, capture_output=True, text=True)
    if build.stdout.strip():
        print(build.stdout)
    if build.stderr.strip():
        print(build.stderr)
    if build.returncode != 0:
        print("コンパイルに失敗しました")
        return build.returncode
    print(f"コンパイル {time.time() - t0:.1f} 秒\n")

    t1 = time.time()
    run = subprocess.run([str(exe)], text=True)
    print(f"\n実行 {time.time() - t1:.1f} 秒")

    if not args.keep:
        try:
            exe.unlink()
            inc.unlink()
            out_dir.rmdir()
        except OSError:
            pass
    else:
        print("残したファイル:", out_dir)
    return run.returncode


if __name__ == "__main__":
    sys.exit(main())
